on:
  push:
    branches: [master]

jobs:
  run-and-upload:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
    - uses: actions/checkout@v3

    - name: "Setup Python environment"
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: "Install dependencies"
      run: pip3 install -r requirements.txt

    - name: "Get Firefox"
      uses: browser-actions/setup-firefox@latest

    - name: "Get geckodriver"
      uses: browser-actions/setup-geckodriver@latest

    - name: "Fetch data"
      run: python3 -u chara.py

    - name: "Check output file"
      id: check-output
      run: "[ -f clothes.json ] && echo ::set-output name=ok::true"

    - name: Authenticate with Google Cloud
      if: ${{ steps.check-output.outputs.ok }}
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.GCP_SA_JSON }}

    - name: Upload data to Google Cloud Storage
      if: ${{ steps.check-output.outputs.ok }}
      uses: google-github-actions/upload-cloud-storage@v0
      with:
        path: clothes.json
        destination: ${{ secrets.GCP_CLOUD_STORAGE_BUCKET }}/clothes.json
